name: Check for file changes with string.xml and label for localization

on:
  pull_request:

jobs:
  
  label_em:
  
    runs-on: ubuntu-latest

    steps:
    
    - name: Check out
      uses: actions/checkout@v1

    - name: check list of files and label if applicable
      run: |
        URL="https://api.github.com/repos/${GITHUB_REPOSITORY}/pulls/${{ github.event.pull_request.number }}/files"
        FILES=$(curl -s -X GET -G $URL | jq -r '.[] | .filename')
        if echo $FILES | grep -q "strings.xml"; then
          URL="https://api.github.com/repos/${GITHUB_REPOSITORY}/issues/${{ github.event.pull_request.number }}/labels"
          curl -s -X POST -H "Accept: application/vnd.github.v3+json" -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" $URL -d '{"labels":["documentation"]}'
        fi
