name: Check for file changes

on:
  pull_request:
    branches: [ develop ]

jobs:
  
  job1:
  
    runs-on: ubuntu-latest

    steps:
    
    - name: Check out
      uses: actions/checkout@v1

    - name: get list of files in PR
      if: github.event.pull_request.open
      run: |
        echo "Stuff"
        
    - name: list files
      run: |
        URL="https://api.github.com/repos/${GITHUB_REPOSITORY}/pulls/${{ github.event.pull_request.number }}/files"
        FILES=$(curl -s -X GET -G $URL | jq -r '.[] | .filename')
        if echo $FILES | grep -q ".kt"; then
          URL="https://api.github.com/repos/${GITHUB_REPOSITORY}/issues/${{ github.event.pull_request.number }}/labels"
          curl -s -X POST -d '{"labels":["localization"]}' -G $URL
